"""Decoding the committed sample clips.

Real files, because the failures this stage handles are properties of real
containers: a truncated transport stream, a variable frame rate whose nominal
value is a lie, bytes that are not a video at all. None of those can be
simulated convincingly by a fake decoder -- they *are* the decoder's behaviour.

The clips are a few kilobytes each and regenerated by
``scripts/make_sample_clips.py``. Skipped when neither decoder is installed,
which is the same arrangement the database tests use.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from fractions import Fraction
from pathlib import Path

import pytest

from multicam_tracker.exceptions import IngestError
from multicam_tracker.ingest import DecoderBackend, FileVideoSource, SourceKind

pytestmark = [pytest.mark.integration, pytest.mark.slow]

MEDIA_DIR = Path(__file__).resolve().parents[2] / "fixtures" / "media"
START = datetime(2026, 8, 10, 14, 0, 0, tzinfo=UTC)

CLEAN = MEDIA_DIR / "sample_clean.mp4"
TRUNCATED = MEDIA_DIR / "sample_truncated.ts"
CORRUPT = MEDIA_DIR / "sample_corrupt.ts"
VFR = MEDIA_DIR / "sample_vfr.mp4"
UNDECODABLE = MEDIA_DIR / "sample_undecodable.mp4"

EXPECTED_FRAMES = 20
EXPECTED_FPS = Fraction(10, 1)
EXPECTED_SIZE = (64, 48)


def _has(module: str) -> bool:
    """Return whether a decoder library is importable.

    Args:
        module: The module name.

    Returns:
        ``True`` when it imports.
    """
    try:
        __import__(module)
    except ImportError:
        return False
    return True


requires_opencv = pytest.mark.skipif(not _has("cv2"), reason="OpenCV is not installed")
requires_pyav = pytest.mark.skipif(not _has("av"), reason="PyAV is not installed")


def _source(path: Path, **overrides: object) -> FileVideoSource:
    """Build a file source over one fixture.

    Args:
        path: The clip.
        **overrides: Field overrides.

    Returns:
        The source.
    """
    fields: dict[str, object] = {"path": path, "camera_id": "cam_01", "start_utc": START}
    fields.update(overrides)
    return FileVideoSource(**fields)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# The ordinary case
# ---------------------------------------------------------------------------


@requires_opencv
def test_a_clean_clip__decodes_with_the_expected_count_and_resolution() -> None:
    """The baseline every other case is a deviation from."""
    with _source(CLEAN) as source:
        frames = list(source.frames())
        properties = source.properties

    assert len(frames) == EXPECTED_FRAMES
    assert properties.resolution == EXPECTED_SIZE
    assert properties.kind is SourceKind.FILE
    assert not source.was_truncated


@requires_opencv
def test_the_frame_rate__is_read_as_an_exact_rational() -> None:
    """A float rate loses 30000/1001, and stage 09 needs the difference."""
    with _source(CLEAN) as source:
        assert source.properties.fps == EXPECTED_FPS
        assert isinstance(source.properties.fps, Fraction)


@requires_opencv
def test_timestamps__advance_by_exactly_one_frame_interval() -> None:
    """Hand-computable at 10 fps: 100 ms apart, from the configured start."""
    with _source(CLEAN) as source:
        stamps = [frame.timestamp_utc for frame in source.frames()]

    assert stamps[0] == START
    assert stamps[-1] == START + timedelta(milliseconds=100 * (EXPECTED_FRAMES - 1))


@requires_opencv
def test_the_camera_clock_offset__is_applied_to_every_frame() -> None:
    """Stage 09's correction, at the single boundary where it belongs."""
    with _source(CLEAN, clock_offset_ms=-45_000) as source:
        frame = next(iter(source.frames()))

    assert frame.raw_timestamp == START
    assert frame.timestamp_utc == START - timedelta(seconds=45)


# ---------------------------------------------------------------------------
# Seeking and limits
# ---------------------------------------------------------------------------


@requires_opencv
def test_seeking__yields_the_right_first_index_and_timestamp() -> None:
    """A seek that renumbered frames would break every later reference to one."""
    with _source(CLEAN, start_frame=5) as source:
        first = next(iter(source.frames()))

    assert first.frame_index == 5
    assert first.timestamp_utc == START + timedelta(milliseconds=500)


@requires_opencv
def test_a_frame_limit__stops_at_the_right_frame() -> None:
    """Bounded work for a preview or a smoke test."""
    with _source(CLEAN, max_frames=4) as source:
        frames = list(source.frames())

    assert [frame.frame_index for frame in frames] == [0, 1, 2, 3]


@requires_opencv
def test_a_duration_limit__stops_after_that_much_source_time() -> None:
    """Expressed in source time, not wall time: a fast decode still stops at 0.5s."""
    with _source(CLEAN, duration_sec=0.5) as source:
        frames = list(source.frames())

    assert len(frames) == 6
    assert frames[-1].timestamp_utc <= START + timedelta(seconds=0.5)


# ---------------------------------------------------------------------------
# Damage
# ---------------------------------------------------------------------------


@requires_opencv
def test_a_truncated_stream__yields_what_is_readable_then_stops_cleanly() -> None:
    """A recording interrupted mid-write is common, not exceptional.

    Treating it as an error would treat a normal event as a failure.
    """
    with _source(TRUNCATED) as source:
        frames = list(source.frames())

    assert 0 < len(frames) < 40
    assert [frame.frame_index for frame in frames] == list(range(len(frames)))


@requires_opencv
def test_a_corrupt_stream__skips_the_damaged_frames_and_keeps_going() -> None:
    """An hour of footage with a hole in it is still most of an hour."""
    source = _source(CORRUPT)
    with source:
        frames = list(source.frames())

    assert len(frames) > 20
    assert source.corrupt_frames_skipped > 0


@requires_pyav
def test_a_file_that_is_not_a_video__raises_naming_what_was_found() -> None:
    """The operator's next step is to transcode or install a decoder.

    Both need to know what the file actually is, so the error carries it.
    """
    with pytest.raises(IngestError, match="no decodable video stream") as excinfo:
        _source(UNDECODABLE).open()

    assert excinfo.value.context["codec"] == "unknown"


@requires_opencv
def test_a_missing_file__is_refused_at_construction() -> None:
    """Fail where the path is wrong, not three layers into a decode."""
    with pytest.raises(IngestError, match="does not exist"):
        _source(MEDIA_DIR / "nonexistent.mp4")


# ---------------------------------------------------------------------------
# The PyAV path
# ---------------------------------------------------------------------------


@requires_pyav
def test_a_variable_rate_file__gets_its_timestamps_from_presentation_times() -> None:
    """The nominal rate is a lie in this file, and following it puts every frame
    after the first gap at the wrong instant.

    The offsets are the ones the fixture was authored with -- uneven on purpose.
    """
    with _source(VFR, prefer_pyav=True) as source:
        offsets = [
            round((frame.timestamp_utc - START).total_seconds(), 3) for frame in source.frames()
        ]

    assert offsets == [0.0, 0.1, 0.2, 0.3, 0.7, 0.8, 1.5, 1.6, 1.7, 3.0]


@requires_pyav
def test_the_nominal_rate_of_a_variable_rate_file__disagrees_with_its_timestamps() -> None:
    """Documents *why* the presentation times are used.

    If the nominal rate were right, the naive arithmetic would work and this
    module would be simpler than it is.
    """
    with _source(VFR, prefer_pyav=True) as source:
        nominal = source.properties.fps
        frames = list(source.frames())

    naive_last = float(Fraction(len(frames) - 1) / nominal)
    actual_last = (frames[-1].timestamp_utc - START).total_seconds()

    assert abs(naive_last - actual_last) > 0.2


@requires_pyav
def test_the_pyav_backend__reports_the_real_codec_name() -> None:
    """OpenCV cannot say what it decoded; PyAV can, and errors need it."""
    with _source(CLEAN, prefer_pyav=True) as source:
        assert source.backend == DecoderBackend.PYAV
        assert source.properties.codec not in {None, "", DecoderBackend.OPENCV}


@requires_pyav
def test_both_backends__agree_on_the_frame_count_of_a_clean_file() -> None:
    """Two decoders, one answer. A disagreement here would make every count
    dependent on which library happened to be installed."""
    with _source(CLEAN) as opencv_source:
        opencv_frames = len(list(opencv_source.frames()))
    with _source(CLEAN, prefer_pyav=True) as pyav_source:
        pyav_frames = len(list(pyav_source.frames()))

    assert opencv_frames == pyav_frames == EXPECTED_FRAMES


# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------


@requires_opencv
def test_the_decoder__is_released_when_iteration_finishes() -> None:
    """A finished file has nothing more to give, and holding its handle is how a
    batch run exhausts its descriptors."""
    source = _source(CLEAN)
    source.open()

    list(source.frames())

    assert not source.is_open


@requires_opencv
def test_opening_many_files_in_sequence__leaves_none_open() -> None:
    """The batch case, against real decoder handles rather than counters."""
    sources = []
    for _ in range(50):
        source = _source(CLEAN, max_frames=1)
        with source:
            list(source.frames())
        sources.append(source)

    assert not any(source.is_open for source in sources)
