"""Explicit conversion between Pydantic domain models and SQLAlchemy rows.

Every mapping is written out by hand rather than generated by attribute copying.
Reflection would appear to work and would silently drop any field whose name
differs between the two layers -- exactly the failure this module exists to
prevent. The cost is that adding a field means editing here too, which is why
:data:`FIELD_CORRESPONDENCE` exists and is asserted by a test: forget the edit
and the suite fails naming the field.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field

from multicam_tracker.db.orm import (
    Base,
    CameraLinkORM,
    CameraORM,
    MatchCandidateORM,
    SightingORM,
    TargetORM,
    TrajectoryHopORM,
    TrajectoryORM,
)
from multicam_tracker.exceptions import StorageError
from multicam_tracker.models import (
    Camera,
    CameraLink,
    CoverageGap,
    MatchCandidate,
    MatchMethod,
    MCTBaseModel,
    ObjectClass,
    ReviewStatus,
    Sighting,
    Target,
    TemporalIntegrity,
    Trajectory,
    TrajectoryHop,
)

__all__ = [
    "FIELD_CORRESPONDENCE",
    "FieldCorrespondence",
    "camera_link_to_domain",
    "camera_link_to_orm",
    "camera_to_domain",
    "camera_to_orm",
    "match_candidate_to_domain",
    "match_candidate_to_orm",
    "sighting_to_domain",
    "sighting_to_orm",
    "target_to_domain",
    "target_to_orm",
    "trajectory_to_domain",
    "trajectory_to_orm",
]


def _to_uuid(value: str, *, field_name: str) -> uuid.UUID:
    """Parse a domain identifier string into a UUID for the database.

    Args:
        value: The identifier as carried by the domain model.
        field_name: Field name reported in the error context.

    Returns:
        The parsed UUID.

    Raises:
        StorageError: If the value is not a well-formed UUID. Raised here rather
            than at the driver so the offending field is named.
    """
    try:
        return uuid.UUID(value)
    except (ValueError, AttributeError, TypeError) as exc:
        raise StorageError(
            "Identifier is not a valid UUID",
            {"field": field_name, "value": str(value)},
        ) from exc


# ---------------------------------------------------------------------------
# Camera
# ---------------------------------------------------------------------------


def camera_to_orm(camera: Camera) -> CameraORM:
    """Convert a :class:`Camera` to its row representation.

    Args:
        camera: The domain model.

    Returns:
        An unattached ORM instance.
    """
    return CameraORM(
        camera_id=camera.camera_id,
        name=camera.name,
        lat=camera.lat,
        lon=camera.lon,
        heading_degrees=camera.heading_degrees,
        clock_offset_ms=camera.clock_offset_ms,
        enabled=camera.enabled,
        notes=camera.notes,
    )


def camera_to_domain(row: CameraORM) -> Camera:
    """Convert a camera row to its domain model.

    Args:
        row: The ORM instance.

    Returns:
        The validated domain model.
    """
    return Camera(
        camera_id=row.camera_id,
        name=row.name,
        lat=row.lat,
        lon=row.lon,
        heading_degrees=row.heading_degrees,
        clock_offset_ms=row.clock_offset_ms,
        enabled=row.enabled,
        notes=row.notes,
    )


# ---------------------------------------------------------------------------
# CameraLink
# ---------------------------------------------------------------------------


def camera_link_to_orm(link: CameraLink) -> CameraLinkORM:
    """Convert a :class:`CameraLink` to its row representation.

    Args:
        link: The domain model.

    Returns:
        An unattached ORM instance.
    """
    return CameraLinkORM(
        from_camera_id=link.from_camera_id,
        to_camera_id=link.to_camera_id,
        min_travel_time_sec=link.min_travel_time_sec,
        max_travel_time_sec=link.max_travel_time_sec,
        distance_meters=link.distance_meters,
        bidirectional=link.bidirectional,
    )


def camera_link_to_domain(row: CameraLinkORM) -> CameraLink:
    """Convert a camera-link row to its domain model.

    Args:
        row: The ORM instance.

    Returns:
        The validated domain model.
    """
    return CameraLink(
        from_camera_id=row.from_camera_id,
        to_camera_id=row.to_camera_id,
        min_travel_time_sec=row.min_travel_time_sec,
        max_travel_time_sec=row.max_travel_time_sec,
        distance_meters=row.distance_meters,
        bidirectional=row.bidirectional,
    )


# ---------------------------------------------------------------------------
# Sighting
# ---------------------------------------------------------------------------


def sighting_to_orm(sighting: Sighting) -> SightingORM:
    """Convert a :class:`Sighting` to its row representation.

    ``plate_folded`` is deliberately not set: it is a generated column that
    Postgres maintains from ``plate_text_normalized``.

    Args:
        sighting: The domain model.

    Returns:
        An unattached ORM instance.
    """
    return SightingORM(
        sighting_id=_to_uuid(sighting.sighting_id, field_name="sighting_id"),
        camera_id=sighting.camera_id,
        timestamp_utc=sighting.timestamp_utc,
        raw_timestamp=sighting.raw_timestamp,
        clock_offset_applied_ms=sighting.clock_offset_applied_ms,
        object_class=sighting.object_class.value,
        detection_confidence=sighting.detection_confidence,
        bbox=list(sighting.bbox),
        frame_index=sighting.frame_index,
        plate_text_raw=sighting.plate_text_raw,
        plate_text_normalized=sighting.plate_text_normalized,
        plate_confidence=sighting.plate_confidence,
        embedding=list(sighting.embedding) if sighting.embedding is not None else None,
        embedding_model_version=sighting.embedding_model_version,
        thumbnail_path=sighting.thumbnail_path,
        source_id=sighting.source_id,
        created_at=sighting.created_at,
    )


def sighting_to_domain(row: SightingORM) -> Sighting:
    """Convert a sighting row to its domain model.

    Args:
        row: The ORM instance.

    Returns:
        The validated domain model.

    Raises:
        pydantic.ValidationError: If the stored row violates a domain invariant,
            which would mean the row was written by something that bypassed this
            layer.
    """
    return Sighting(
        sighting_id=str(row.sighting_id),
        camera_id=row.camera_id,
        timestamp_utc=row.timestamp_utc,
        raw_timestamp=row.raw_timestamp,
        clock_offset_applied_ms=row.clock_offset_applied_ms,
        object_class=ObjectClass(row.object_class),
        detection_confidence=row.detection_confidence,
        bbox=list(row.bbox),
        frame_index=row.frame_index,
        plate_text_raw=row.plate_text_raw,
        plate_text_normalized=row.plate_text_normalized,
        plate_confidence=row.plate_confidence,
        embedding=[float(component) for component in row.embedding]
        if row.embedding is not None
        else None,
        embedding_model_version=row.embedding_model_version,
        thumbnail_path=row.thumbnail_path,
        source_id=row.source_id,
        created_at=row.created_at,
    )


# ---------------------------------------------------------------------------
# Target
# ---------------------------------------------------------------------------


def target_to_orm(target: Target) -> TargetORM:
    """Convert a :class:`Target` to its row representation.

    Args:
        target: The domain model.

    Returns:
        An unattached ORM instance.
    """
    return TargetORM(
        target_id=_to_uuid(target.target_id, field_name="target_id"),
        label=target.label,
        plate_query=target.plate_query,
        reference_embeddings=(
            [list(vector) for vector in target.reference_embeddings]
            if target.reference_embeddings is not None
            else None
        ),
        created_at=target.created_at,
        active=target.active,
    )


def target_to_domain(row: TargetORM) -> Target:
    """Convert a target row to its domain model.

    Args:
        row: The ORM instance.

    Returns:
        The validated domain model.
    """
    return Target(
        target_id=str(row.target_id),
        label=row.label,
        plate_query=row.plate_query,
        reference_embeddings=(
            [[float(component) for component in vector] for vector in row.reference_embeddings]
            if row.reference_embeddings is not None
            else None
        ),
        created_at=row.created_at,
        active=row.active,
    )


# ---------------------------------------------------------------------------
# MatchCandidate
# ---------------------------------------------------------------------------


def match_candidate_to_orm(candidate: MatchCandidate) -> MatchCandidateORM:
    """Convert a :class:`MatchCandidate` to its row representation.

    Args:
        candidate: The domain model.

    Returns:
        An unattached ORM instance.
    """
    return MatchCandidateORM(
        target_id=_to_uuid(candidate.target_id, field_name="target_id"),
        sighting_id=_to_uuid(candidate.sighting_id, field_name="sighting_id"),
        match_method=candidate.match_method.value,
        match_score=candidate.match_score,
        plate_edit_distance=candidate.plate_edit_distance,
        embedding_similarity=candidate.embedding_similarity,
        review_status=candidate.review_status.value,
    )


def match_candidate_to_domain(row: MatchCandidateORM) -> MatchCandidate:
    """Convert a match-candidate row to its domain model.

    Args:
        row: The ORM instance.

    Returns:
        The validated domain model.
    """
    return MatchCandidate(
        sighting_id=str(row.sighting_id),
        target_id=str(row.target_id),
        match_method=MatchMethod(row.match_method),
        match_score=row.match_score,
        plate_edit_distance=row.plate_edit_distance,
        embedding_similarity=row.embedding_similarity,
        review_status=ReviewStatus(row.review_status),
    )


# ---------------------------------------------------------------------------
# Trajectory
# ---------------------------------------------------------------------------


def trajectory_to_orm(trajectory: Trajectory) -> tuple[TrajectoryORM, list[TrajectoryHopORM]]:
    """Convert a :class:`Trajectory` to its row and its hop rows.

    Hops carry an explicit ``position`` because SQL result order is not
    guaranteed without an ORDER BY, and a trajectory whose hops came back
    shuffled would describe a different route.

    Args:
        trajectory: The domain model.

    Returns:
        The trajectory row and its ordered hop rows.
    """
    trajectory_uuid = _to_uuid(trajectory.trajectory_id, field_name="trajectory_id")

    row = TrajectoryORM(
        trajectory_id=trajectory_uuid,
        target_id=_to_uuid(trajectory.target_id, field_name="target_id"),
        sighting_ids=[
            _to_uuid(sighting.sighting_id, field_name="sightings[].sighting_id")
            for sighting in trajectory.sightings
        ],
        overall_confidence=trajectory.overall_confidence,
        start_time_utc=trajectory.start_time_utc,
        end_time_utc=trajectory.end_time_utc,
        gaps=[gap.to_json_dict() for gap in trajectory.gaps],
        temporal_integrity=(
            trajectory.temporal_integrity.to_json_dict()
            if trajectory.temporal_integrity is not None
            else None
        ),
        requires_recomputation=trajectory.requires_recomputation,
    )

    hops = [
        TrajectoryHopORM(
            trajectory_id=trajectory_uuid,
            position=position,
            from_sighting_id=_to_uuid(hop.from_sighting_id, field_name="hops[].from_sighting_id"),
            to_sighting_id=_to_uuid(hop.to_sighting_id, field_name="hops[].to_sighting_id"),
            from_camera_id=hop.from_camera_id,
            to_camera_id=hop.to_camera_id,
            elapsed_sec=hop.elapsed_sec,
            topology_plausible=hop.topology_plausible,
            hop_confidence=hop.hop_confidence,
        )
        for position, hop in enumerate(trajectory.hops)
    ]

    return row, hops


def trajectory_to_domain(
    row: TrajectoryORM,
    hop_rows: list[TrajectoryHopORM],
    sightings: list[Sighting],
) -> Trajectory:
    """Rebuild a :class:`Trajectory` from its rows and its resolved sightings.

    Sightings are passed in rather than loaded here so the mapper stays free of
    database access; the repository resolves them in ``sighting_ids`` order.

    Args:
        row: The trajectory row.
        hop_rows: Its hop rows, which are sorted by ``position`` here regardless
            of the order they arrive in.
        sightings: The trajectory's sightings, in chronological order.

    Returns:
        The validated domain model.
    """
    ordered_hops = sorted(hop_rows, key=lambda hop: hop.position)

    return Trajectory(
        trajectory_id=str(row.trajectory_id),
        target_id=str(row.target_id),
        sightings=sightings,
        hops=[
            TrajectoryHop(
                from_sighting_id=str(hop.from_sighting_id),
                to_sighting_id=str(hop.to_sighting_id),
                from_camera_id=hop.from_camera_id,
                to_camera_id=hop.to_camera_id,
                elapsed_sec=hop.elapsed_sec,
                topology_plausible=hop.topology_plausible,
                hop_confidence=hop.hop_confidence,
            )
            for hop in ordered_hops
        ],
        overall_confidence=row.overall_confidence,
        start_time_utc=row.start_time_utc,
        end_time_utc=row.end_time_utc,
        gaps=[CoverageGap.from_json_dict(gap) for gap in row.gaps],
        temporal_integrity=(
            TemporalIntegrity.from_json_dict(row.temporal_integrity)
            if row.temporal_integrity is not None
            else None
        ),
        requires_recomputation=row.requires_recomputation,
    )


# ---------------------------------------------------------------------------
# Field-set correspondence
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FieldCorrespondence:
    """Declares how one domain model's fields line up with one table's columns.

    Args:
        domain_model: The Pydantic model.
        orm_model: The SQLAlchemy model.
        renamed: Domain field name -> column name, where the two differ.
        domain_only: Domain field -> why it has no column of its own.
        orm_only: Column -> why it has no domain field.
    """

    domain_model: type[MCTBaseModel]
    orm_model: type[Base]
    renamed: dict[str, str] = field(default_factory=dict)
    domain_only: dict[str, str] = field(default_factory=dict)
    orm_only: dict[str, str] = field(default_factory=dict)

    def unmapped_domain_fields(self) -> set[str]:
        """Return domain fields with neither a matching column nor a justification.

        Returns:
            Field names that would be silently dropped on the way to the
            database. Any non-empty result is a bug.
        """
        columns = orm_column_names(self.orm_model)
        return {
            name
            for name in self.domain_model.model_fields
            if name not in self.domain_only and self.renamed.get(name, name) not in columns
        }

    def unmapped_orm_columns(self) -> set[str]:
        """Return columns with neither a matching domain field nor a justification.

        Returns:
            Column names that would never be populated from a domain model.
        """
        populated = {
            self.renamed.get(name, name)
            for name in self.domain_model.model_fields
            if name not in self.domain_only
        }
        return orm_column_names(self.orm_model) - populated - set(self.orm_only)


FIELD_CORRESPONDENCE: tuple[FieldCorrespondence, ...] = (
    FieldCorrespondence(Camera, CameraORM),
    FieldCorrespondence(CameraLink, CameraLinkORM),
    FieldCorrespondence(
        Sighting,
        SightingORM,
        orm_only={
            "plate_folded": (
                "Generated column maintained by Postgres from plate_text_normalized. "
                "It exists to index fuzzy lookups and is never written or read by "
                "the domain layer."
            )
        },
    ),
    FieldCorrespondence(Target, TargetORM),
    FieldCorrespondence(MatchCandidate, MatchCandidateORM),
    FieldCorrespondence(
        Trajectory,
        TrajectoryORM,
        renamed={"sightings": "sighting_ids"},
        domain_only={
            "hops": (
                "Stored in the trajectory_hops table with an explicit position "
                "column, so hop order survives a query without an ORDER BY."
            )
        },
    ),
    FieldCorrespondence(
        TrajectoryHop,
        TrajectoryHopORM,
        orm_only={
            "trajectory_id": "Parent key; the domain model is nested inside its Trajectory.",
            "position": "Explicit ordering, since SQL result order is not guaranteed.",
        },
    ),
)
"""Every domain-model/table pair, with each mismatch justified in writing.

A field added to a domain model but not to its table produces an entry in
:meth:`FieldCorrespondence.unmapped_domain_fields`, which a unit test asserts is
empty. That is the mechanism that makes "mapping must be total" enforceable
rather than a promise.
"""


def correspondence_for(domain_model: type[MCTBaseModel]) -> FieldCorrespondence:
    """Return the correspondence entry for ``domain_model``.

    Args:
        domain_model: The Pydantic model to look up.

    Returns:
        Its correspondence declaration.

    Raises:
        StorageError: If the model has no declared correspondence, which means a
            new entity was added without a mapping.
    """
    for entry in FIELD_CORRESPONDENCE:
        if entry.domain_model is domain_model:
            return entry
    raise StorageError(
        "No field correspondence declared for this domain model",
        {"model": domain_model.__name__},
    )


def orm_column_names(orm_model: type[Base]) -> set[str]:
    """Return the column names of an ORM model.

    Args:
        orm_model: The SQLAlchemy model.

    Returns:
        Its column keys.
    """
    return {column.key for column in orm_model.__table__.columns}


def domain_field_names(domain_model: type[MCTBaseModel]) -> set[str]:
    """Return the field names of a domain model.

    Args:
        domain_model: The Pydantic model.

    Returns:
        Its declared field names.
    """
    return set(domain_model.model_fields)
